variables:
  # Docker Hub repository details
  FRONTEND_IMAGE: bhuvaneshraj/grademaster-frontend
  BACKEND_IMAGE: bhuvaneshraj/grademaster-backend
  DOCKER_TAG: latest

# Build the frontend Docker image
build-frontend:
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  script:
    - echo "Building the frontend Docker image..."
    - docker build -t $FRONTEND_IMAGE:$DOCKER_TAG ./frontend
    - echo "Pushing the frontend Docker image to Docker Hub..."
    - docker push $FRONTEND_IMAGE:$DOCKER_TAG
  only:
    - master

# Build the backend Docker image
build-backend:
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - echo "Building the backend Docker image..."
    - docker build -t $BACKEND_IMAGE:$DOCKER_TAG ./backend
    - echo "Pushing the backend Docker image to Docker Hub..."
    - docker push $BACKEND_IMAGE:$DOCKER_TAG
  only:
    - master

