version: '3.8'

services:
  # Node.js Server 1
  node1:
    build:
      context: .
    container_name: node1
    ports:
      - "3501:3500"
    networks:
      - my_network

  # Node.js Server 2
  node2:
    build:
      context: .
    container_name: node2
    ports:
      - "3502:3500"
    networks:
      - my_network

  # Node.js Server 3
  node3:
    build:
      context: .
    container_name: node3
    ports:
      - "3503:3500"
    networks:
      - my_network

  # NGINX Load Balancer
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "3600:3600" # Expose port 3600 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
